/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;


import dss.classes.Divida;
import dss.classes.Facade;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class ConsultarDividas extends javax.swing.JDialog {
    private String emailUser;
    private int i;
    private Facade f;
    /**
     * Creates new form VerMensagemAdmin
     */
    public ConsultarDividas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.i=0;
    }
    
    public ConsultarDividas(String email) throws SQLException {
      this.emailUser=email;
      i=0;
      initComponents();
      f=new Facade();
      String nome = f.getNome(email);
      
      List<Divida> mensagemUser = f.getDividas(email, nome);
      
      if(mensagemUser.isEmpty()) {
      
           JOptionPane.showMessageDialog(null, "Não têm dividas");
          this.mensagem.setText("");
          
      }
      else {
      
           Divida m = mensagemUser.get(i);
                   
                  
                  this.mensagem.setText(m.toString());
          
      
      }
      this.mensagem.setEditable(false);
      
      this.idDividaLabel.setVisible(false);
      this.identificadorDivida.setVisible(false);
      this.ok.setVisible(false);
      this.valorApagarLabel.setVisible(false);
      this.valorDivida.setVisible(false);
      
      
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagem = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        pagar = new javax.swing.JButton();
        idDividaLabel = new javax.swing.JLabel();
        identificadorDivida = new javax.swing.JTextField();
        valorApagarLabel = new javax.swing.JLabel();
        valorDivida = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText(" Dívidas: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 16, 204, 24);

        mensagem.setColumns(20);
        mensagem.setRows(5);
        jScrollPane1.setViewportView(mensagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(25, 46, 331, 255);

        jButton1.setText("seguinte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(244, 319, 73, 23);

        jLabel2.setText(">");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(327, 323, 37, 14);

        jButton2.setText("anterior");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 319, 71, 23);

        jLabel3.setText("<");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 323, 21, 14);

        sair.setText("Voltar ao menu Inicial");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(10, 410, 135, 31);

        pagar.setText("Pagar");
        pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarMouseClicked(evt);
            }
        });
        getContentPane().add(pagar);
        pagar.setBounds(230, 410, 86, 31);

        idDividaLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        idDividaLabel.setText("Identificador da Divida");
        getContentPane().add(idDividaLabel);
        idDividaLabel.setBounds(410, 30, 165, 32);
        getContentPane().add(identificadorDivida);
        identificadorDivida.setBounds(410, 60, 165, 29);

        valorApagarLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        valorApagarLabel.setText("Valor a pagar");
        getContentPane().add(valorApagarLabel);
        valorApagarLabel.setBounds(420, 110, 165, 24);
        getContentPane().add(valorDivida);
        valorDivida.setBounds(410, 140, 165, 30);

        ok.setText("Pagar");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(510, 210, 69, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/15749738_10208020464682452_1065624881_n.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 459);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        try {
            // TODO add your handling code here:
            new InicioComCasa(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_sairMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            List<Divida> mensagemUser=new ArrayList<>();
             String nome = f.getNome(this.emailUser);
           mensagemUser = f.getDividas(this.emailUser, nome);
           i++;
            if(i>=mensagemUser.size()) {
            
                JOptionPane.showMessageDialog(null, "Nao tem mais dividas");
            
            }
            else {
                if(mensagemUser.isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais dividas");
                    
                }
                else {
                
                
                   Divida m = mensagemUser.get(i);
                   
                  this.mensagem.setText("");
                  this.mensagem.setText(m.toString());
                }
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            // TODO add your handling code here:
            List<Divida> mensagemUser=new ArrayList<>();
            String nome = f.getNome(this.emailUser);
      
           mensagemUser = f.getDividas(this.emailUser, nome);
            i--;
            
            if(i<0) {
                
                JOptionPane.showMessageDialog(null, "Nao pode andar mais para trás");
                
                
            }
            else {
                if(mensagemUser.isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais dividas");
                    
                }
                else {
                   
                Divida m = mensagemUser.get(i);
                   
                  this.mensagem.setText("");
                  this.mensagem.setText(m.toString());
                    
                }
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void pagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarMouseClicked
        // TODO add your handling code here:
        
        this.idDividaLabel.setVisible(true);
      this.identificadorDivida.setVisible(true);
      this.ok.setVisible(true);
      this.valorApagarLabel.setVisible(true);
      this.valorDivida.setVisible(true);
      this.pagar.setVisible(false);
        
        
        
    }//GEN-LAST:event_pagarMouseClicked

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        // TODO add your handling code here:
        try {
        int id =Integer.parseInt(this.identificadorDivida.getText());
        
        if(f.getIdDivida(id)==0) {
           JOptionPane.showMessageDialog(null, "Id não existe");
           
            
        }
        else {
             
             float valorInt = Float.parseFloat(this.valorDivida.getText());
             float valor =f.getValorDivida(id);
             float valorConta = f.getDinheiro(emailUser);
             if(valor ==valorInt && valorConta>=valorInt) {
               f.pagarDivida(id);
               f.pagarEmprestimo(valor);
               f.retiraSaldo(valor, emailUser);
               i=0;
               this.mensagem.setText("");
               JOptionPane.showMessageDialog(null, "Divida paga");
                 
                 
             }
             else {
             
                  JOptionPane.showMessageDialog(null, "Valor introduzido incorrecto");
                  
                 
             }
            
        
        }
        
        
        
        }
        catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Valor invalido");
            
        
        }
        
        this.valorDivida.setText("");
        this.identificadorDivida.setText("");
        
     
        
        
        
        
    }//GEN-LAST:event_okMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idDividaLabel;
    private javax.swing.JTextField identificadorDivida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensagem;
    private javax.swing.JButton ok;
    private javax.swing.JButton pagar;
    private javax.swing.JButton sair;
    private javax.swing.JLabel valorApagarLabel;
    private javax.swing.JTextField valorDivida;
    // End of variables declaration//GEN-END:variables
}
