/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;

import dss.classes.Facade;
import dss.classes.Morador;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class EditarDados extends javax.swing.JDialog {
   private String emailUser;
   private Facade f;
    /**
     * Creates new form EditarDados
     */
    public EditarDados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
    
      
    }
    
    public EditarDados(String email) {
    this.emailUser=email;
    initComponents();
    f=new Facade();
    
    this.nomeAlterado.setVisible(false);
    this.confirmarNome.setVisible(false);
    this.ano.setVisible(false);
    this.anoLabel.setVisible(false);
    this.mes.setVisible(false);
    this.mesLabel.setVisible(false);
    this.dia.setVisible(false);
    this.diaLabel.setVisible(false);
    this.confirmarData.setVisible(false);
    this.numeroAlterado.setVisible(false);
    this.confirmarNumero.setVisible(false);
    this.passeAlterada.setVisible(false);
    this.confirmarPasse.setVisible(false);
    this.emailAlterado.setVisible(false);
    this.confirmarEmail.setVisible(false);
    
    this.nomeCampo.setEditable(false);
    this.dataCampo.setEditable(false);
    this.numeroCampo.setEditable(false);
    this.passeWordCampo.setEditable(false);
    this.emailCampo.setEditable(false);
    
    
    
    
    inserCampos();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        diaLabel = new javax.swing.JLabel();
        mesLabel = new javax.swing.JLabel();
        anoLabel = new javax.swing.JLabel();
        ano = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        dia = new javax.swing.JComboBox<>();
        editarNome = new javax.swing.JButton();
        editarData = new javax.swing.JButton();
        nomeAlterado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataCampo = new javax.swing.JTextField();
        numeroCampo = new javax.swing.JTextField();
        editarNumero = new javax.swing.JButton();
        confirmarNome = new javax.swing.JButton();
        confirmarData = new javax.swing.JButton();
        confirmarNumero = new javax.swing.JButton();
        numeroAlterado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editarPasse = new javax.swing.JButton();
        passeWordCampo = new javax.swing.JPasswordField();
        passeAlterada = new javax.swing.JPasswordField();
        confirmarPasse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        emailCampo = new javax.swing.JTextField();
        editarEmail = new javax.swing.JButton();
        emailAlterado = new javax.swing.JTextField();
        confirmarEmail = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 108, 14);
        getContentPane().add(nomeCampo);
        nomeCampo.setBounds(10, 36, 160, 20);

        jLabel2.setText("Data de Nascimento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 108, 21);

        diaLabel.setText("Dia");
        getContentPane().add(diaLabel);
        diaLabel.setBounds(293, 90, 33, 14);

        mesLabel.setText("Mes");
        getContentPane().add(mesLabel);
        mesLabel.setBounds(380, 90, 29, 14);

        anoLabel.setText("Ano");
        getContentPane().add(anoLabel);
        anoLabel.setBounds(446, 90, 36, 14);

        ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900", "1899", "1898", "1897", "1896", "1895", "1894", "1893", "1892", "1891 ", "1890", "1889", "1888", "1887", "1886", "1885", "1884", "1883", "1882", "1881 ", "1880", "1879", "1878", "1877", "1876", "1875", "1874", "1873", "1872", "1871 ", "1870", "1869", "1868", "1867", "1866", "1865", "1864", "1863", "1862", "1861 ", "1860", "1859", "1858", "1857", "1856", "1855", "1854", "1853", "1852", "1851 ", "1850", "1849", "1848", "1847", "1846", "1845", "1844", "1843", "1842", "1841 ", "1840", "1839", "1838", "1837", "1836", "1835", "1834", "1833", "1832", "1831 ", "1830", "1829", "1828", "1827", "1826", "1825", "1824", "1823", "1822", "1821 ", "1820", "1819", "1818", "1817", "1816" }));
        getContentPane().add(ano);
        ano.setBounds(446, 115, 67, 20);

        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(mes);
        mes.setBounds(380, 115, 50, 20);

        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(dia);
        dia.setBounds(293, 115, 58, 20);

        editarNome.setText("editar");
        editarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarNomeMouseClicked(evt);
            }
        });
        getContentPane().add(editarNome);
        editarNome.setBounds(190, 40, 80, 23);

        editarData.setText("editar");
        editarData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarDataMouseClicked(evt);
            }
        });
        getContentPane().add(editarData);
        editarData.setBounds(136, 118, 80, 23);
        getContentPane().add(nomeAlterado);
        nomeAlterado.setBounds(300, 40, 160, 20);

        jLabel3.setText("Número de telemovel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 174, 108, 22);
        getContentPane().add(dataCampo);
        dataCampo.setBounds(10, 123, 108, 20);
        getContentPane().add(numeroCampo);
        numeroCampo.setBounds(10, 210, 108, 20);

        editarNumero.setText("editar");
        editarNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarNumeroMouseClicked(evt);
            }
        });
        getContentPane().add(editarNumero);
        editarNumero.setBounds(140, 210, 80, 23);

        confirmarNome.setText("confirmar");
        confirmarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarNomeMouseClicked(evt);
            }
        });
        getContentPane().add(confirmarNome);
        confirmarNome.setBounds(481, 35, 90, 23);

        confirmarData.setText("confirmar");
        confirmarData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarDataMouseClicked(evt);
            }
        });
        getContentPane().add(confirmarData);
        confirmarData.setBounds(341, 153, 90, 23);

        confirmarNumero.setText("confirmar");
        confirmarNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarNumeroMouseClicked(evt);
            }
        });
        getContentPane().add(confirmarNumero);
        confirmarNumero.setBounds(468, 205, 90, 23);
        getContentPane().add(numeroAlterado);
        numeroAlterado.setBounds(293, 210, 160, 20);

        jLabel4.setText("Palavra Passe");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 248, 108, 26);

        editarPasse.setText("editar");
        editarPasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarPasseMouseClicked(evt);
            }
        });
        getContentPane().add(editarPasse);
        editarPasse.setBounds(136, 295, 80, 23);
        getContentPane().add(passeWordCampo);
        passeWordCampo.setBounds(8, 296, 110, 20);
        getContentPane().add(passeAlterada);
        passeAlterada.setBounds(293, 295, 160, 20);

        confirmarPasse.setText("confirmar");
        confirmarPasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarPasseMouseClicked(evt);
            }
        });
        getContentPane().add(confirmarPasse);
        confirmarPasse.setBounds(470, 290, 90, 23);

        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 350, 108, 23);
        getContentPane().add(emailCampo);
        emailCampo.setBounds(10, 380, 108, 20);

        editarEmail.setText("editar");
        editarEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarEmailMouseClicked(evt);
            }
        });
        getContentPane().add(editarEmail);
        editarEmail.setBounds(136, 380, 80, 23);
        getContentPane().add(emailAlterado);
        emailAlterado.setBounds(293, 386, 160, 20);

        confirmarEmail.setText("confirmar");
        confirmarEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarEmailMouseClicked(evt);
            }
        });
        getContentPane().add(confirmarEmail);
        confirmarEmail.setBounds(481, 380, 90, 23);

        voltar.setText("voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(10, 430, 83, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 590, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarNomeMouseClicked
        // TODO add your handling code here:
    this.nomeAlterado.setVisible(true);
    this.confirmarNome.setVisible(true);
    this.nomeAlterado.setText("");
    
    
    this.ano.setVisible(false);
    this.anoLabel.setVisible(false);
    this.mes.setVisible(false);
    this.mesLabel.setVisible(false);
    this.dia.setVisible(false);
    this.diaLabel.setVisible(false);
    this.confirmarData.setVisible(false);
    this.numeroAlterado.setVisible(false);
    this.confirmarNumero.setVisible(false);
    this.passeAlterada.setVisible(false);
    this.confirmarPasse.setVisible(false);
    this.emailAlterado.setVisible(false);
    this.confirmarEmail.setVisible(false);
    
        
        
        
    }//GEN-LAST:event_editarNomeMouseClicked

    private void editarDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarDataMouseClicked
        // TODO add your handling code here:
    
    this.ano.setVisible(true);
    this.anoLabel.setVisible(true);
    this.mes.setVisible(true);
    this.mesLabel.setVisible(true);
    this.dia.setVisible(true);
    this.diaLabel.setVisible(true);
    this.confirmarData.setVisible(true);
      
    
    this.nomeAlterado.setVisible(false);
    this.confirmarNome.setVisible(false);
    this.numeroAlterado.setVisible(false);
    this.confirmarNumero.setVisible(false);
    this.passeAlterada.setVisible(false);
    this.confirmarPasse.setVisible(false);
    this.emailAlterado.setVisible(false);
    this.confirmarEmail.setVisible(false);
    
    
        
        
        
        
    }//GEN-LAST:event_editarDataMouseClicked

    private void editarNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarNumeroMouseClicked
        // TODO add your handling code here:
    this.numeroAlterado.setVisible(true);
    this.confirmarNumero.setVisible(true);
    this.numeroAlterado.setText("");
    
    
    this.nomeAlterado.setVisible(false);
    this.confirmarNome.setVisible(false);
    this.ano.setVisible(false);
    this.anoLabel.setVisible(false);
    this.mes.setVisible(false);
    this.mesLabel.setVisible(false);
    this.dia.setVisible(false);
    this.diaLabel.setVisible(false);
    this.confirmarData.setVisible(false);
    this.passeAlterada.setVisible(false);
    this.confirmarPasse.setVisible(false);
    this.emailAlterado.setVisible(false);
    this.confirmarEmail.setVisible(false);
    
    
        
        
        
        
    }//GEN-LAST:event_editarNumeroMouseClicked

    private void editarPasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarPasseMouseClicked
        // TODO add your handling code here:
        this.passeAlterada.setVisible(true);
        this.confirmarPasse.setVisible(true);
        this.passeAlterada.setText("");
        
    this.numeroAlterado.setVisible(false);
    this.confirmarNumero.setVisible(false);
    this.nomeAlterado.setVisible(false);
    this.confirmarNome.setVisible(false);
    this.ano.setVisible(false);
    this.anoLabel.setVisible(false);
    this.mes.setVisible(false);
    this.mesLabel.setVisible(false);
    this.dia.setVisible(false);
    this.diaLabel.setVisible(false);
    this.confirmarData.setVisible(false);
    this.emailAlterado.setVisible(false);
    this.confirmarEmail.setVisible(false);
    
        
    }//GEN-LAST:event_editarPasseMouseClicked

    private void editarEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarEmailMouseClicked
        // TODO add your handling code here:
    this.emailAlterado.setVisible(true);
    this.confirmarEmail.setVisible(true);
    this.emailAlterado.setText("");
    
    
    this.passeAlterada.setVisible(false);
    this.confirmarPasse.setVisible(false);
    this.numeroAlterado.setVisible(false);
    this.confirmarNumero.setVisible(false);
    this.nomeAlterado.setVisible(false);
    this.confirmarNome.setVisible(false);
    this.ano.setVisible(false);
    this.anoLabel.setVisible(false);
    this.mes.setVisible(false);
    this.mesLabel.setVisible(false);
    this.dia.setVisible(false);
    this.diaLabel.setVisible(false);
    this.confirmarData.setVisible(false);
   
        
        
        
    }//GEN-LAST:event_editarEmailMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
       try {
           // TODO add your handling code here:
           if(f.getCasa(emailUser)==0) {
             new InicioComCasa(emailUser).setVisible(true);
             this.dispose();
           }
           else {
           new Inicio(this.emailUser).setVisible(true);
           this.dispose();
           }
       } catch (SQLException ex) {
           Logger.getLogger(EditarDados.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_voltarMouseClicked

    
    
    private void confirmarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarNomeMouseClicked
       try {
           // TODO add your handling code here:
           f.actualizaNome(this.nomeAlterado.getText(), emailUser);
            JOptionPane.showMessageDialog(null, "Nome alterado com sucesso");
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Impossivel alterar o nome");
       }
        
        
        
    }//GEN-LAST:event_confirmarNomeMouseClicked

    private void confirmarDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarDataMouseClicked
        // TODO add your handling code here:
        if(validarData()) {
        
            int anos = Integer.parseInt(this.ano.getSelectedItem().toString());
            int dias = Integer.parseInt(this.dia.getSelectedItem().toString());
            int meses = Integer.parseInt(this.mes.getSelectedItem().toString());
            
            GregorianCalendar dataNascimento = new GregorianCalendar(anos, meses-1, dias);
            
            try {
                f.actualizaData(emailUser, dataNascimento);
                 JOptionPane.showMessageDialog(null, "Data alterada com sucesso");
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Impossivel alterar a data");
            }
            
           
            
        
        }
        else  JOptionPane.showMessageDialog(null, "Data invalida");
        
        
    }//GEN-LAST:event_confirmarDataMouseClicked

    private void confirmarNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarNumeroMouseClicked
       try {
           // TODO add your handling code here:
            Integer.parseInt(this.nomeAlterado.getText());
           if(f.actualizarNumero(emailUser,this.numeroAlterado.getText())==0) {
            JOptionPane.showMessageDialog(null, "Numero alterado com sucesso");
           }
           else {
           JOptionPane.showMessageDialog(null, "Numero de telemovel repetido");
               
           }
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Impossivel de adicionar esse numero");
       }
        
        
    }//GEN-LAST:event_confirmarNumeroMouseClicked

    private void confirmarPasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarPasseMouseClicked
       try {
           // TODO add your handling code here:

          f.actualizarPass(String.valueOf(this.passeAlterada.getPassword()), emailUser);
           JOptionPane.showMessageDialog(null, "Palavra passe alterada com sucesso");
           
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Impossivel de alterar a palavra passe");
       }
        
    }//GEN-LAST:event_confirmarPasseMouseClicked

    private void confirmarEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarEmailMouseClicked
       try {
           // TODO add your handling code here:

           if(f.actualizarEmail(this.emailAlterado.getText(), emailUser)==0) {
           JOptionPane.showMessageDialog(null, "Email alterado com sucesso");
           }
           else JOptionPane.showMessageDialog(null, "Email repetido");
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "Email repetido");
       }
        
    }//GEN-LAST:event_confirmarEmailMouseClicked

    private void inserCampos() {
       try {
           Morador u = f.getMorador(this.emailUser);
           this.nomeCampo.setText(u.getNome());
           this.emailCampo.setText(this.emailUser);
           this.passeWordCampo.setText(u.getPassword());
           this.numeroCampo.setText(u.getNrTelemovel());
           String data = ""+u.getDataNascimento().get(Calendar.YEAR) 
                    + "-"+ (u.getDataNascimento().get(Calendar.MONTH)+1)+"-"
                   + u.getDataNascimento().get(Calendar.DAY_OF_MONTH) ;
           
           this.dataCampo.setText(data);
           
           
           
       } catch (SQLException ex) {
           Logger.getLogger(EditarDados.class.getName()).log(Level.SEVERE, null, ex);
       }
    
    }
    
    
    
    
    
    
    private boolean validarData() {
    
       int anos = Integer.parseInt(this.ano.getSelectedItem().toString());
       int dias = Integer.parseInt(this.dia.getSelectedItem().toString());
       int meses = Integer.parseInt(this.mes.getSelectedItem().toString());
    
       if(((anos % 4 == 0) && (anos % 100 != 0)) || (anos % 400 == 0) ) {
         
            if(meses ==2) {
            
                return dias>=1 && dias <=29;
            }
            
            else {
            
                if(meses ==4 || meses ==6 || meses == 9 || meses ==11) {
                    
                    return dias >=1 && dias <=30;
                    
                    
                
                }
            
            
            }
         
       }
       
       else {
       
           if(meses ==2) {
            
               return dias>=1 && dias <=28;
            }
            
            else {
            
                if(meses ==4 || meses ==6 || meses == 9 || meses ==11) {
                    
                    return dias >=1 && dias <=30;
                    
                }
       
       }

    
    }
    return true;
   }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ano;
    private javax.swing.JLabel anoLabel;
    private javax.swing.JButton confirmarData;
    private javax.swing.JButton confirmarEmail;
    private javax.swing.JButton confirmarNome;
    private javax.swing.JButton confirmarNumero;
    private javax.swing.JButton confirmarPasse;
    private javax.swing.JTextField dataCampo;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JButton editarData;
    private javax.swing.JButton editarEmail;
    private javax.swing.JButton editarNome;
    private javax.swing.JButton editarNumero;
    private javax.swing.JButton editarPasse;
    private javax.swing.JTextField emailAlterado;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JLabel mesLabel;
    private javax.swing.JTextField nomeAlterado;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextField numeroAlterado;
    private javax.swing.JTextField numeroCampo;
    private javax.swing.JPasswordField passeAlterada;
    private javax.swing.JPasswordField passeWordCampo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
