/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;


import dss.classes.Conta;
import dss.classes.Facade;
import dss.classes.Pagamento;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class ApagarConta extends javax.swing.JDialog {
    private String emailUser;
    private int i;
    private Facade f;
    /**
     * Creates new form VerMensagemAdmin
     */
    public ApagarConta (java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.i=0;
    }
    
    public ApagarConta (String email) throws SQLException {
      this.emailUser=email;
      i=0;
      initComponents();
      f=new Facade();
      
      List<Conta> mensagemUser = f.contasTotais();
      
      if(mensagemUser.isEmpty()) {
      
           JOptionPane.showMessageDialog(null, "Não têm contas para apagar");
          this.mensagem.setText("");
          
      }
      else {
          
          
      
           Conta m = mensagemUser.get(i);
           Map<String,Pagamento> p = f.getPagamento( m.getIdentificador());
                  m.setPagam(p);
           
                  
                  this.mensagem.setText(m.toString());
          
      
      }
      this.mensagem.setEditable(false);
      
      this.idDividaLabel.setVisible(false);
      this.identificadorDivida.setVisible(false);
      this.ok.setVisible(false);
      
      
      
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagem = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        pagar = new javax.swing.JButton();
        idDividaLabel = new javax.swing.JLabel();
        identificadorDivida = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel1.setText("Contas");

        mensagem.setColumns(20);
        mensagem.setRows(5);
        jScrollPane1.setViewportView(mensagem);

        jButton1.setText("seguinte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText(">");

        jButton2.setText("anterior");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel3.setText("<");

        sair.setText("Voltar ao menu Inicial");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });

        pagar.setText("Apagar");
        pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarMouseClicked(evt);
            }
        });

        idDividaLabel.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        idDividaLabel.setText("Identificador do Pagamento");

        identificadorDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificadorDividaActionPerformed(evt);
            }
        });

        ok.setText("Apagar");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/15749738_10208020464682452_1065624881_n.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificadorDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton2)
                .addGap(144, 144, 144)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sair)
                .addGap(115, 115, 115)
                .addComponent(pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(idDividaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(identificadorDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jButton1)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(idDividaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        try {
            // TODO add your handling code here:
            new Administrar(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_sairMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            List<Conta> mensagemUser=new ArrayList<>();
             
           mensagemUser = f.contasTotais();
           
           
           i++;
            if(i>=mensagemUser.size()) {
            
                JOptionPane.showMessageDialog(null, "Nao tem mais contas para apagar");
            
            }
            else {
                if(mensagemUser.isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais contas para apagar");
                    
                }
                else {
                     if(i<0) {i=0;}
                
                   Conta m = mensagemUser.get(i);
                   Map<String,Pagamento> p = f.getPagamento( m.getIdentificador());
                  m.setPagam(p);
                  this.mensagem.setText("");
                  this.mensagem.setText(m.toString());
                }
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            // TODO add your handling code here:
            List<Conta> mensagemUser=new ArrayList<>();
            
      
           mensagemUser = f.contasTotais();
            i--;
            
            if(i<0) {
                
                JOptionPane.showMessageDialog(null, "Nao pode andar mais para trás");
                
                
            }
            else {
                if(i>=mensagemUser.size()) {i=0;}
                
                if(mensagemUser.isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais contas para apagar");
                    
                }
                else {
                   
                Conta m = mensagemUser.get(i);
                   
                 Map<String,Pagamento> p = f.getPagamento( m.getIdentificador());
                  m.setPagam(p);
            
                  this.mensagem.setText("");
                  this.mensagem.setText(m.toString());
                    
                }
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void pagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarMouseClicked
        // TODO add your handling code here:
        
      this.idDividaLabel.setVisible(true);
      this.identificadorDivida.setVisible(true);
      this.ok.setVisible(true);
      this.pagar.setVisible(false);
        
        
        
    }//GEN-LAST:event_pagarMouseClicked

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        // TODO add your handling code here:
        try {
        int id =Integer.parseInt(this.identificadorDivida.getText());
        
        if(f.verificaContaAdmin(id)==0) {
           JOptionPane.showMessageDialog(null, "Id invalido");
           
            
        }
        else {
            
           
               f.apagarConta(id);
               JOptionPane.showMessageDialog(null, "Conta apagada com sucesso");
           
         
           
        }
        
        }
        catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Valor invalido");
            
        
        }
        i=0;
        this.identificadorDivida.setText("");
        this.mensagem.setText("");
        
     
        
        
        
        
    }//GEN-LAST:event_okMouseClicked

    private void identificadorDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificadorDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificadorDividaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idDividaLabel;
    private javax.swing.JTextField identificadorDivida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensagem;
    private javax.swing.JButton ok;
    private javax.swing.JButton pagar;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
