/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;

import dss.classes.Facade;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class Inicio extends javax.swing.JDialog {
    private String emailUser;
    private Facade f;
    /**
     * Creates new form Inicio
     */
    public Inicio(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        initComponents();
        
    }
    
    public Inicio(String email) throws SQLException {
       this.emailUser=email;
       f=new Facade();
        initComponents();
        
        if(f.nrAdmin()==0) {
            this.criarGrupo.setVisible(true);
        
        }
        else {
            this.criarGrupo.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarGrupo = new javax.swing.JButton();
        editarDados = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        criarGrupo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        criarGrupo.setText("Criar Grupo");
        criarGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarGrupoMouseClicked(evt);
            }
        });

        editarDados.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        editarDados.setText("Editar dados Pessoais");
        editarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarDadosMouseClicked(evt);
            }
        });

        sair.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adminpainelseg.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(editarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(criarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(sair))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(editarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(criarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_sairMouseClicked

    private void editarDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarDadosMouseClicked
        // TODO add your handling code here:
        new EditarDados(this.emailUser).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_editarDadosMouseClicked

    private void criarGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarGrupoMouseClicked
        try {
            // TODO add your handling code here:
           f.putAdmin(emailUser);
            JOptionPane.showMessageDialog(null, "É agora admin");
            new Administrar(emailUser).setVisible(true);
            this.dispose();
            
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Impossivel torna-se admin");
        }
        
        
        
    }//GEN-LAST:event_criarGrupoMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarGrupo;
    private javax.swing.JButton editarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
