/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;


import dss.classes.Conta;
import dss.classes.Facade;
import dss.classes.Pagamento;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class VerContasPagasAdmin extends javax.swing.JDialog {
    private String emailUser;
    private int i;
    private Facade f;
    /**
     * Creates new form VerMensagemAdmin
     */
    public VerContasPagasAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.i=0;
    }
    
    public VerContasPagasAdmin(String email) throws SQLException {
      this.emailUser=email;
      i=0;
      initComponents();
      f=new Facade();
      
      List<Conta> mensagemUser = f.getContasPagasAdmin();
      
      if(mensagemUser.isEmpty()) {
      
           JOptionPane.showMessageDialog(null, "Não possui contas pagas");
          this.mensagem.setText("");
          
      }
      else {
          Map<String,Pagamento> pagamentos = new HashMap<>();
      
           Conta m = mensagemUser.get(i);
                   pagamentos=f.getPagamento(m.getIdentificador());
                   m.setPagam(pagamentos);
                  
                  this.mensagem.setText(m.imprimeContasPagas());
          
      
      }
      this.mensagem.setEditable(false);
      
      
      
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagem = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("                                 Contas Pagas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 309, 24);

        mensagem.setColumns(20);
        mensagem.setRows(5);
        jScrollPane1.setViewportView(mensagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(82, 53, 407, 249);

        jButton1.setText("seguinte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 320, 73, 23);

        jLabel2.setText(">");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 314, 37, 30);

        jButton2.setText("anterior");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(107, 320, 71, 23);

        jLabel3.setText("<");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(82, 324, 21, 14);

        sair.setText("Voltar ao menu Inicial");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(430, 430, 135, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/15749738_10208020464682452_1065624881_n.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 580, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        try {
            // TODO add your handling code here:
            new Administrar(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VerContasPagasAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_sairMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            List<Conta> mensagemUser=new ArrayList<>();
                mensagemUser = f.getContasPagasAdmin();

           i++;
            if(i>=mensagemUser.size()) {
            
                JOptionPane.showMessageDialog(null, "Nao tem mais contas pagas");
            
            }
            else {
                
                 if(mensagemUser .isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais contas");
                    
                }
                else {
                
                   Map<String,Pagamento> pagamentos = new HashMap<>();
                
                   Conta m = mensagemUser.get(i);
                   pagamentos=f.getPagamento(m.getIdentificador());
                   m.setPagam(pagamentos);
                   
                  this.mensagem.setText("");
                  this.mensagem.setText(m.imprimeContasPagas());
                
            }
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VerContasPagas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            // TODO add your handling code here:
            List<Conta> mensagemUser=new ArrayList<>();
            
      
                mensagemUser = f.getContasPagasAdmin();
            i--;
            
            if(i<0) {
                
                JOptionPane.showMessageDialog(null, "Nao pode andar mais para trás");
                
                
            }
            else {
                
                 if(mensagemUser .isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais contas");
                    
                }
                else {
                
                Map<String,Pagamento> pagamentos = new HashMap<>();
                   
                Conta m = mensagemUser.get(i);
                pagamentos=f.getPagamento(m.getIdentificador());
                   m.setPagam(pagamentos);   
                
                  this.mensagem.setText("");
                  this.mensagem.setText(m.imprimeContasPagas());
                    
                
                
                 }   
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerContasPagas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensagem;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
