/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;

import dss.classes.Conta;
import dss.classes.Facade;
import dss.classes.Pagamento;
import java.sql.SQLException;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author gil
 */
public class ContaExtraOrdinaria extends javax.swing.JDialog {
   private String email;
   private String descrisao;
   private GregorianCalendar dataLimite;
   private float valorTotal;
   private Map<String,Float> percentagemApagar;
   private Facade f;
   private Map<String,Pagamento> pagamento;
   private float percetagemTotal;
   private DefaultListModel dlm = new DefaultListModel();
   private DefaultListModel dlm2 = new DefaultListModel();
   
    /**
     * Creates new form DividaExtraOrdinaria
     */
    
    
    
    
    public ContaExtraOrdinaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

     public ContaExtraOrdinaria(String email,String assunto,GregorianCalendar g,float valor) throws SQLException {
         this.email=email;
         this.descrisao=assunto;
         this.dataLimite=g;
         this.valorTotal=valor;
         this.f=new Facade();
         this.percentagemApagar=new HashMap<>();
         this.pagamento = new HashMap<>();
         this.percetagemTotal=0;
         initComponents();
         
         List<String> emailsUtilizadores = f.getUserCasa();
         
         
         
          for (String e : emailsUtilizadores) {
               dlm.addElement(e);
               
           }
           this.utilizadoresCasa.setModel(dlm);
         
         
         
         this.percentagem.setVisible(false);
         this.valorPercentagem.setVisible(false);
         this.ok.setVisible(false);
         this.label.setVisible(false);
         this.utilizadoresApagar.setVisible(false);
         this.remover.setVisible(false);
         this.confirmar.setVisible(false);
         
         
         
         
     
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        utilizadoresCasa = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        utilizadoresApagar = new javax.swing.JList<>();
        remover = new javax.swing.JButton();
        percentagem = new javax.swing.JLabel();
        valorPercentagem = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Utilizadores presentes na casa");

        utilizadoresCasa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(utilizadoresCasa);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setText("voltar ao menu anterior");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarMouseClicked(evt);
            }
        });

        jButton2.setText("adicionar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label.setText("Utilizadores que irão pagar");

        utilizadoresApagar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(utilizadoresApagar);

        remover.setText("remover");
        remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerMouseClicked(evt);
            }
        });

        percentagem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        percentagem.setText("Percentagem a pagar");

        ok.setText("ok");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(percentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valorPercentagem))
                            .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(remover, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(remover))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(percentagem)
                        .addGap(18, 18, 18)
                        .addComponent(valorPercentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new AdicionaConta(email).setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
       
       DefaultListModel model = (DefaultListModel) utilizadoresCasa.getModel();
       int selectedIndex = utilizadoresCasa.getSelectedIndex();
       
       if (selectedIndex != -1) {
            
            this.percentagem.setVisible(true);
           this.valorPercentagem.setVisible(true);
           this.ok.setVisible(true);
           
        }    
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        // TODO add your handling code here:
  try {
        float valorInt = Float.parseFloat(this.valorPercentagem.getText());
        
        if(valorInt>0 && valorInt<=1) {
          this.percetagemTotal=this.percetagemTotal+valorInt;
          
           
           
                     if(this.percetagemTotal>1) {
                         JOptionPane.showMessageDialog(null, "Introduza ontra percentagem");
                        this.percetagemTotal=this.percetagemTotal-valorInt;
                         
                     }
                    else {
                            


                            DefaultListModel model = (DefaultListModel) utilizadoresCasa.getModel();

                            int selectedIndex = utilizadoresCasa.getSelectedIndex();


                            if (selectedIndex != -1) {
                                dlm2.addElement(this.utilizadoresCasa.getSelectedValue() +" - percentagem : "+valorInt);

                                this.label.setVisible(true);
                                this.utilizadoresApagar.setVisible(true);
                                this.remover.setVisible(true);
                                this.confirmar.setVisible(true);

                                String emailS = this.utilizadoresCasa.getSelectedValue();
                                String nome = f.getNome(emailS);

                                this.percentagemApagar.put(emailS,valorInt);


                                Pagamento p = new Pagamento(emailS,nome,valorInt*this.valorTotal);

                                this.pagamento.put(emailS, p);


                                model.remove(selectedIndex);
                            }



                            this.utilizadoresApagar.setModel(dlm2);
                        }
        
        
        }
        else {
        
            JOptionPane.showMessageDialog(null, "Introduza um valor maior que zero e menor que 1");
            
        
        }
        
        if(this.percetagemTotal==1) {
        
             JOptionPane.showMessageDialog(null, "Percentagem total igual a 1");
            
        
        }
        
        
      } catch (Exception e) {
        
            JOptionPane.showMessageDialog(null, "Dados invalidos");
        
        }
        
     this.valorPercentagem.setText("");
        
    }//GEN-LAST:event_okMouseClicked

    private void removerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerMouseClicked
        // TODO add your handling code here:
        
        
        
       
        DefaultListModel model = (DefaultListModel) utilizadoresApagar.getModel();
        int selectedIndex = utilizadoresApagar.getSelectedIndex();
        
        if (selectedIndex != -1) {
            
             String []partes = this.utilizadoresApagar.getSelectedValue().split("-");
            String ks =partes[0].trim();
             dlm.addElement(ks);
             this.percetagemTotal=percetagemTotal-this.percentagemApagar.get(partes[0]);
             
             this.pagamento.remove(ks);
            
            model.remove(selectedIndex);
          
        }
        
        this.utilizadoresCasa.setModel(dlm);
        
    }//GEN-LAST:event_removerMouseClicked

    private void confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseClicked
        // TODO add your handling code here:
       try {
        if(this.pagamento.isEmpty()) {
          JOptionPane.showMessageDialog(null, "Não introduzi nenhum utilizador");
            
        }
        else {
            if(this.percetagemTotal<1) {
                 JOptionPane.showMessageDialog(null, "Falta introduzir utilizadores");
            
            }
            else {
            int tamanho=this.pagamento.size();
        
            Conta m =new Conta(this.descrisao,"Extraordinaria",valorTotal,this.dataLimite,0,tamanho,0,0);
            this.f.inserConta(m,this.pagamento);
             
             
             JOptionPane.showMessageDialog(null, "Conta inserida com sucesso");
             
             new Administrar(email).setVisible(true);
             this.dispose();
            
            
        
        }
        }
        
       } catch (Exception e) {
       
            JOptionPane.showMessageDialog(null, "Não foi possivel introduzir a conta");
           
       }
        
        
    }//GEN-LAST:event_confirmarMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JButton ok;
    private javax.swing.JLabel percentagem;
    private javax.swing.JButton remover;
    private javax.swing.JList<String> utilizadoresApagar;
    private javax.swing.JList<String> utilizadoresCasa;
    private javax.swing.JTextField valorPercentagem;
    // End of variables declaration//GEN-END:variables
}
