/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;

import dss.classes.Facade;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class ConvidarUser extends javax.swing.JDialog {
   private Facade f;
   private String emailUser;
   private DefaultListModel dlm = new DefaultListModel();
   private DefaultListModel dlm2 = new DefaultListModel();
   private List<String> a;

    /**
     * Creates new form ConvidarUser
     */
    public ConvidarUser(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
       
    }
    
    public ConvidarUser(String email) throws SQLException {
       this.emailUser=email;
       this.f=new Facade();
       initComponents();
       this.a=new ArrayList<>();
       
       
           List<String> emails =this.f.getUser();
           
           for (String e : emails) {
               dlm.addElement(e);
               
           }
           this.listaUser.setModel(dlm);
       
           this.listaAdicionada.setVisible(false);
           this.remover.setVisible(false);
           this.confirmar.setVisible(false);
           this.label.setVisible(false);
       
       
        
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUser = new javax.swing.JList<>();
        adicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAdicionada = new javax.swing.JList<>();
        remover = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setText("voltar ao menu anterior");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Utilizadores com conta criada");

        listaUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaUser);

        adicionar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        adicionar.setText("adicionar utilizador a casa");
        adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarMouseClicked(evt);
            }
        });

        listaAdicionada.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaAdicionada);

        remover.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        remover.setText("Remover");
        remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerMouseClicked(evt);
            }
        });

        label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label.setText("Utilizadores adicionados");

        confirmar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        confirmar.setText("confirmar");
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmar)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(remover, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmar))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remover)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       try {
           // TODO add your handling code here:
           new Administrar(emailUser).setVisible(true);
           this.dispose();
       } catch (SQLException ex) {
           Logger.getLogger(ConvidarUser.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_jButton1MouseClicked
    private void adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarMouseClicked

        
       
       
       
      
       
       DefaultListModel model = (DefaultListModel) listaUser.getModel();
        int selectedIndex = listaUser.getSelectedIndex();
        if (selectedIndex != -1) {
            dlm2.addElement(this.listaUser.getSelectedValue());
            
            this.listaAdicionada.setVisible(true);
           this.remover.setVisible(true);
           this.confirmar.setVisible(true);
           this.label.setVisible(true);
             a.add(this.listaUser.getSelectedValue());
            model.remove(selectedIndex);
        }
       
       
       this.listaAdicionada.setModel(dlm2);
        
        
        
        
    }//GEN-LAST:event_adicionarMouseClicked

    private void removerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerMouseClicked
        // TODO add your handling code here:
        
        
        
        DefaultListModel model = (DefaultListModel) listaAdicionada.getModel();
        int selectedIndex = listaAdicionada.getSelectedIndex();
        if (selectedIndex != -1) {
            dlm.addElement(this.listaAdicionada.getSelectedValue());
            a.remove(this.listaAdicionada.getSelectedValue());
            model.remove(selectedIndex);
        }
        
        this.listaUser.setModel(dlm);
        
        
        
        
        
    }//GEN-LAST:event_removerMouseClicked

    private void confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseClicked
        // TODO add your handling code here:4
       
          
        
            try {
                if(a.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Não adicionou qualquer utilizador ");
                
                }
                else {
                for(String em : this.a) {
        
                f.inserCasa(emailUser,em);
            
                }
                
                JOptionPane.showMessageDialog(null, "Utilizadores adicionados ");
                this.dlm2.removeAllElements();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ConvidarUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_confirmarMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JList<String> listaAdicionada;
    private javax.swing.JList<String> listaUser;
    private javax.swing.JButton remover;
    // End of variables declaration//GEN-END:variables
}
