/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;


import dss.classes.Facade;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gil
 */
public class InicioComCasa extends javax.swing.JDialog {
    private String emailUser;
    private Facade f;
    /**
     * Creates new form InicioComCasa
     */
    public InicioComCasa(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        initComponents();
        f=new Facade();
         
        
        
    }
    
    public InicioComCasa(String email) throws SQLException {
       f=new Facade();
        this.emailUser=email;
        initComponents();
        float saldo;
        
        saldo =f.getDinheiro(this.emailUser);
        
        this.saldoCasa.setText(saldo+"");
        this.saldoCasa.setEditable(false);
        
        if(f.getEmailAdmin().equals(this.emailUser)) {
        
            this.admin.setVisible(true);
            this.sair.setVisible(false);
            this.mensagemAdmin.setVisible(false);
            
        }
        
        else {this.admin.setVisible(false);
              this.sair.setVisible(true);
              this.mensagemAdmin.setVisible(true);
              }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagemAdmin = new javax.swing.JButton();
        pagarDivida = new javax.swing.JButton();
        emprestimos = new javax.swing.JButton();
        pagarConta = new javax.swing.JButton();
        verContasPagas = new javax.swing.JButton();
        carregarConta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saldoCasa = new javax.swing.JTextField();
        sair = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mensagemAdmin.setText("Ver mensagens do admin");
        mensagemAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mensagemAdminMouseClicked(evt);
            }
        });

        pagarDivida.setText("Consultar Dividas");
        pagarDivida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarDividaMouseClicked(evt);
            }
        });

        emprestimos.setText("Consultar emprestimos");
        emprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emprestimosMouseClicked(evt);
            }
        });

        pagarConta.setText("Pagar Conta");
        pagarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarContaMouseClicked(evt);
            }
        });

        verContasPagas.setText("Ver Contas Pagas");
        verContasPagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContasPagasMouseClicked(evt);
            }
        });

        carregarConta.setText("Atualizar  Saldo");
        carregarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carregarContaMouseClicked(evt);
            }
        });

        jLabel1.setText("O teu saldo é :");

        sair.setText("Logout");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });

        admin.setText("Voltar ao Menu Admin");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        jButton1.setText("Editar dados pessoais");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("System Costs");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contas.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(pagarDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(emprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(pagarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(verContasPagas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(saldoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328)
                .addComponent(sair))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(admin))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mensagemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(carregarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(pagarDivida)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emprestimos)
                    .addComponent(pagarConta))
                .addGap(41, 41, 41)
                .addComponent(verContasPagas)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(sair))))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(admin))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(mensagemAdmin))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(carregarConta))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_sairMouseClicked

    private void mensagemAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensagemAdminMouseClicked
        try {
            // TODO add your handling code here:
            new VerMesagemAdmin(this.emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(InicioComCasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mensagemAdminMouseClicked

    private void emprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimosMouseClicked
        try {
            // TODO add your handling code here:
            new VerEmprestimos(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(InicioComCasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_emprestimosMouseClicked

    private void verContasPagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContasPagasMouseClicked
        try {
            // TODO add your handling code here:
            new VerContasPagas(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(InicioComCasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_verContasPagasMouseClicked

    private void carregarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carregarContaMouseClicked
        // TODO add your handling code here:
        
        new ActualizarSaldo(this.emailUser).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_carregarContaMouseClicked

    private void pagarDividaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarDividaMouseClicked
        try {
            // TODO add your handling code here:
            
            new ConsultarDividas(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(InicioComCasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_pagarDividaMouseClicked

    private void pagarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarContaMouseClicked
        try {
            // TODO add your handling code here:
            new ConsultarConta(emailUser).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(InicioComCasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_pagarContaMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        new JanelaAdmin(this.emailUser).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_adminMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         new EditarDados(emailUser).setVisible(true);
         this.dispose();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton carregarConta;
    private javax.swing.JButton emprestimos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mensagemAdmin;
    private javax.swing.JButton pagarConta;
    private javax.swing.JButton pagarDivida;
    private javax.swing.JButton sair;
    private javax.swing.JTextField saldoCasa;
    private javax.swing.JButton verContasPagas;
    // End of variables declaration//GEN-END:variables
}
