/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.gui;

import dss.classes.Divida;
import dss.classes.Emprestimo;
import dss.classes.Facade;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class VerEmprestimo extends javax.swing.JDialog {
   private String email;
   private Facade f;
   private int iDivida;
   private int iEmprestimo;
   private boolean carregou;
    /**
     * Creates new form VerEmprestimo
     */
    public VerEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VerEmprestimo(String email) throws SQLException {
      this.f=new Facade();
      this.email=email;
      iDivida=0;
      iEmprestimo=0;
      this.carregou=false;
      initComponents();
      
      List<Divida> dividas = f.getDividasAdmin();
      
      if(dividas.isEmpty()) {
      
           JOptionPane.showMessageDialog(null, "Não existe dividas na casa");
          this.dividasA.setText("");
          
      }
      else {
          
          
      
           Divida m = dividas.get(iDivida);
           
                  
                  this.dividasA.setText(m.toString());
          
      
      }
      
      List<Emprestimo> emp = f.getEmprestimosAdmin();
      
      if(emp.isEmpty()) {
      
           JOptionPane.showMessageDialog(null, "Não existe emprestimos na casa");
          this.dividasA.setText("");
          
      }
      else {
          
          
      
           Emprestimo m = emp.get(iEmprestimo);
           
                  
                  this.emprestimosA.setText(m.imprimeEmprestimo());
        
      }
      
       this.valorIntroduzido.setVisible(false);
       this.apagar.setVisible(false);
       this.emprestimosA.setEditable(false);
       this.dividasA.setEditable(false);
        this.label.setVisible(false);
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dividasA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emprestimosA = new javax.swing.JTextArea();
        proximoDivida = new javax.swing.JButton();
        anteriorDivida = new javax.swing.JButton();
        anteriorEmprestimo = new javax.swing.JButton();
        proximoEmprestimo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        valorIntroduzido = new javax.swing.JTextField();
        apagar = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Dividas da casa");

        dividasA.setColumns(20);
        dividasA.setRows(5);
        jScrollPane1.setViewportView(dividasA);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Emprestimos da casa");

        emprestimosA.setColumns(20);
        emprestimosA.setRows(5);
        jScrollPane2.setViewportView(emprestimosA);

        proximoDivida.setText("proximo");
        proximoDivida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proximoDividaMouseClicked(evt);
            }
        });

        anteriorDivida.setText("anterior");
        anteriorDivida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anteriorDividaMouseClicked(evt);
            }
        });

        anteriorEmprestimo.setText("anterior");
        anteriorEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anteriorEmprestimoMouseClicked(evt);
            }
        });

        proximoEmprestimo.setText("proximo");
        proximoEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proximoEmprestimoMouseClicked(evt);
            }
        });

        jButton5.setText("Apagar divida");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Apagar Emprestimo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        valorIntroduzido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorIntroduzidoFocusGained(evt);
            }
        });

        apagar.setText("apagar");
        apagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagarMouseClicked(evt);
            }
        });

        jButton8.setText("voltar ao menu anterior");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel3.setText(">");

        jLabel4.setText("<");

        jLabel5.setText(">");

        jLabel6.setText("<");

        label.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        label.setText(" Introduza o id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anteriorDivida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proximoDivida)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(proximoEmprestimo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(86, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anteriorEmprestimo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valorIntroduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(apagar)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorDivida)
                    .addComponent(proximoDivida)
                    .addComponent(anteriorEmprestimo)
                    .addComponent(proximoEmprestimo)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorIntroduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apagar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jButton8)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
       try {
           // TODO add your handling code here:
           new Administrar(email).setVisible(true);
           this.dispose();
       } catch (SQLException ex) {
           Logger.getLogger(VerEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void proximoDividaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proximoDividaMouseClicked
        // TODO add your handling code here:
         List<Divida> dividasLista=new ArrayList<>();
         try {    
           dividasLista = f.getDividasAdmin();
           
           
           iDivida++;
            if(iDivida>=dividasLista.size()) {
            
                JOptionPane.showMessageDialog(null, "Nao tem mais dividas");
            
            }
            else {
                if(dividasLista .isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais dividas");
                    
                }
                else {
                
                
                  Divida m = dividasLista .get(iDivida);
                   
            
                  this.dividasA.setText("");
                 this.dividasA.setText(m.toString());
                }
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_proximoDividaMouseClicked

    private void anteriorDividaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorDividaMouseClicked
         try {
            // TODO add your handling code here:
            List<Divida> mensagemUser=new ArrayList<>();
            
      
           mensagemUser = f.getDividasAdmin();
            iDivida--;
            
            if(iDivida<0) {
                
                JOptionPane.showMessageDialog(null, "Nao pode andar mais para trás");
                
                
            }
            else {
                if(mensagemUser.isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais dividas");
                    
                }
                else {
                   
                Divida m = mensagemUser.get(iDivida);
                   
                 
            
                  this.dividasA.setText("");
                  this.dividasA.setText(m.toString());
                    
                }
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_anteriorDividaMouseClicked

    private void proximoEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proximoEmprestimoMouseClicked
        // TODO add your handling code here:
        List<Emprestimo> dividasLista=new ArrayList<>();
         try {    
          dividasLista = f.getEmprestimoAdmin();
           
           
           iEmprestimo++;
            if( iEmprestimo>=dividasLista.size()) {
            
                JOptionPane.showMessageDialog(null, "Nao tem mais emprestimos");
            
            }
            else {
                if(dividasLista .isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais emprestimos");
                    
                }
                else {
                
                
                  Emprestimo m = dividasLista .get( iEmprestimo);
                   
            
                  this.emprestimosA.setText("");
                 this.emprestimosA.setText(m.imprimeEmprestimo());
                }
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_proximoEmprestimoMouseClicked

    private void anteriorEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorEmprestimoMouseClicked
       try {
            // TODO add your handling code here:
            List<Emprestimo> mensagemUser=new ArrayList<>();
            
      
           mensagemUser = f.getEmprestimoAdmin();
            iEmprestimo--;
            
            if( iEmprestimo<0) {
                
                JOptionPane.showMessageDialog(null, "Nao pode andar mais para trás");
                
                
            }
            else {
                if(mensagemUser.isEmpty()) {
                
                     JOptionPane.showMessageDialog(null, "Nao tem mais emprestimos");
                    
                }
                else {
                   
                Emprestimo m = mensagemUser.get( iEmprestimo);
                   
                 
            
                  this.emprestimosA.setText("");
                  this.emprestimosA.setText(m.imprimeEmprestimo());
                    
                }
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_anteriorEmprestimoMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
        this.valorIntroduzido.setVisible(true);
        this.apagar.setVisible(true);
         this.label.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        this.valorIntroduzido.setVisible(true);
        this.apagar.setVisible(true);
         this.label.setVisible(true);
       this.carregou=true;
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void valorIntroduzidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorIntroduzidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_valorIntroduzidoFocusGained

    private void apagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagarMouseClicked
        // TODO add your handling code here:
        if(this.carregou) {
        
            try {
            
        int idEmprestimo = Integer.parseInt(this.valorIntroduzido.getText());
        
        if(f.getIdEmprestimo(idEmprestimo)==0) {
        
             JOptionPane.showMessageDialog(null, "Id invalido");
        
        }
        else {
        
            f.dropEmprestimo(idEmprestimo);
            JOptionPane.showMessageDialog(null, "Emprestimo apagado ");
            this.emprestimosA.setText("");
            this.iEmprestimo=0;
            
        
        }
        
        
        
        }
        catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Id invalido");
            
        
        }
        
        }
        
        
        
        else {
        
            try {
            
        int idDivida = Integer.parseInt(this.valorIntroduzido.getText());
        
        if(f.getValorDivida(idDivida)==0) {
        
             JOptionPane.showMessageDialog(null, "Id invalido");
        
        }
        else {
        
            f.dropDivida(idDivida);
            JOptionPane.showMessageDialog(null, "Divida apagada");
            this.dividasA.setText("");
            this.iDivida=0;
        }
        
        
        
        }
        catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Id invalido");
            
        
        }
            
        
        
        }  
        this.label.setVisible(false);
      this.valorIntroduzido.setVisible(false);
        this.apagar.setVisible(false);
          
        
        
    }//GEN-LAST:event_apagarMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorDivida;
    private javax.swing.JButton anteriorEmprestimo;
    private javax.swing.JButton apagar;
    private javax.swing.JTextArea dividasA;
    private javax.swing.JTextArea emprestimosA;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JButton proximoDivida;
    private javax.swing.JButton proximoEmprestimo;
    private javax.swing.JTextField valorIntroduzido;
    // End of variables declaration//GEN-END:variables
}
